#!/bin/bash -e

SCRIPT_DIR="$(cd "$(dirname "$BASH_SOURCE[0]")" >/dev/null 2>&1 && pwd)"

ZEPHYR_TOOLCHAIN_VERSION="0.17.2"
ZEPHYR_SDK="zephyr-sdk-${ZEPHYR_TOOLCHAIN_VERSION}"
ZEPHYR_SDK_INSTALL_DIR_ROOT="/opt"
ZEPHYR_SDK_INSTALL_DIR="${ZEPHYR_SDK_INSTALL_DIR_ROOT}/${ZEPHYR_SDK}"
PYTHON_VENV_DIR="${SCRIPT_DIR}/.venv"

PROJECT_DIR="${SCRIPT_DIR}/project"
FIRMWARE_DIR="${PROJECT_DIR}/firmware"
SRC_DIR="${FIRMWARE_DIR}/app"
WEST_WORKSPACE="${PROJECT_DIR}/.west"